export const tickerInfo = [
    {
      "titulo": "3M Company",
      "simbolo": "MMM",
      "Trading Symbol": "MMM",
      "ratio": "5",
    },
    {
      "titulo": "Abbott Labs",
      "simbolo": "ABT",
      "Trading Symbol": "ABT",
      "ratio": "4",
    },
    {
      "titulo": "ABERCROMBIE & FITCH CO.",
      "simbolo": "ANF",
      "Trading Symbol": "ANF",
      "ratio": "1",
    },
    {
      "titulo": "ADECOAGRO S.A.",
      "simbolo": "ADGO",
      "Trading Symbol": "AGRO",
      "ratio": "1:2",
    },
    {
      "titulo": "ADOBE SYSTEMS INCORPORATED",
      "simbolo": "ADBE",
      "Trading Symbol": "ADBE",
      "ratio": "22",
    },
    {
      "titulo": "ADVANCED MICRO DEVICES, INC.",
      "simbolo": "AMD",
      "Trading Symbol": "AMD",
      "ratio": "1:2",
    },
    {
      "titulo": "AEGON N.V.",
      "simbolo": "AEG",
      "Trading Symbol": "AEG",
      "ratio": "1",
    },
    {
      "titulo": "Agnico Eagle Mines Limited",
      "simbolo": "AEM",
      "Trading Symbol": "AEM",
      "ratio": "3",
    },
    {
      "titulo": "ALIBABA GROUP HOLDING LIMITED",
      "simbolo": "BABA",
      "Trading Symbol": "BABA",
      "ratio": "9",
    },
    {
      "titulo": "Alphabet Inc.",
      "simbolo": "GOOGL",
      "Trading Symbol": "GOOGL",
      "ratio": "58",
    },
    {
      "titulo": "ALTABA INC",
      "simbolo": "AABA",
      "Trading Symbol": "AABA",
      "ratio": "3",
    },
    {
      "titulo": "Altria Group Inc.",
      "simbolo": "MO",
      "Trading Symbol": "MO",
      "ratio": "4",
    },
    {
      "titulo": "Aluminum Corp of China",
      "simbolo": "ACH",
      "Trading Symbol": "ACH",
      "ratio": "1",
    },
    {
      "titulo": "AMAZON.COM, INC.",
      "simbolo": "AMZN",
      "Trading Symbol": "AMZN",
      "ratio": "144",
    },
    {
      "titulo": "AMBEV S.A.",
      "simbolo": "ABEV",
      "Trading Symbol": "ABEV",
      "ratio": "1:3",
    },
    {
      "titulo": "America Movil",
      "simbolo": "AMX",
      "Trading Symbol": "AMX",
      "ratio": "1",
    },
    {
      "titulo": "American Express Co",
      "simbolo": "AXP",
      "Trading Symbol": "AXP",
      "ratio": "5",
    },
    {
      "titulo": "American International Group (AIG)",
      "simbolo": "AIG",
      "Trading Symbol": "AIG",
      "ratio": "5",
    },
    {
      "titulo": "Amgen Inc.",
      "simbolo": "AMGN",
      "Trading Symbol": "AMGN",
      "ratio": "10",
    },
    {
      "titulo": "Analog Devices",
      "simbolo": "ADI",
      "Trading Symbol": "ADI",
      "ratio": "3",
    },
    {
      "titulo": "Apple Inc.",
      "simbolo": "AAPL",
      "Trading Symbol": "AAPL",
      "ratio": "10",
    },
    {
      "titulo": "Applied Materials Inc.",
      "simbolo": "AMAT",
      "Trading Symbol": "AMAT",
      "ratio": "5",
    },
    {
      "titulo": "Howmet Aerospace Inc.",
      "simbolo": "HWM",
      "Trading Symbol": "HWM",
      "ratio": "1",
    },
    {
      "titulo": "ARCOS DORADOS HOLDINGS INC.",
      "simbolo": "ARCO",
      "Trading Symbol": "ARCO",
      "ratio": "1:2",
    },
    {
      "titulo": "Astrazeneca PLC",
      "simbolo": "AZN",
      "Trading Symbol": "AZN",
      "ratio": "2",
    },
    {
      "titulo": "AT &T Inc.",
      "simbolo": "T",
      "Trading Symbol": "T",
      "ratio": "3",
    },
    {
      "titulo": "Automatic Data Processing Inc",
      "simbolo": "ADP",
      "Trading Symbol": "ADP",
      "ratio": "6",
    },
    {
      "titulo": "Avery Dennison Corp.",
      "simbolo": "AVY",
      "Trading Symbol": "AVY",
      "ratio": "3",
    },
    {
      "titulo": "Avis Budget Group Inc.",
      "simbolo": "CAR",
      "Trading Symbol": "CAR",
      "ratio": "1",
    },
    {
      "titulo": "Natura & Co Holding S.A.",
      "simbolo": "NTCO",
      "Trading Symbol": "NTCO",
      "ratio": "1",
    },
    {
      "titulo": "BAIDU, INC.",
      "simbolo": "BIDU",
      "Trading Symbol": "BIDU",
      "ratio": "11",
    },
    {
      "titulo": "Banco Bradesco S.A.",
      "simbolo": "BBD",
      "Trading Symbol": "BBD",
      "ratio": "1",
    },
    {
      "titulo": "Banco Santander (BRASIL) S.A.",
      "simbolo": "BSBR",
      "Trading Symbol": "BSBR",
      "ratio": "1",
    },
    {
      "titulo": "BANCO SANTANDER (ADR)",
      "simbolo": "SAN",
      "Trading Symbol": "SAN",
      "ratio": "1:4",
    },
    {
      "titulo": "Bank of America Corporation",
      "simbolo": "BA.C",
      "Trading Symbol": "BAC",
      "ratio": "2",
    },
    {
      "titulo": "Barclays Bank PLC",
      "simbolo": "BCS",
      "Trading Symbol": "BCS",
      "ratio": "1",
    },
    {
      "titulo": "Barrick Gold Corp",
      "simbolo": "GOLD",
      "Trading Symbol": "GOLD",
      "ratio": "1",
    },
    {
      "titulo": "BASF SE",
      "simbolo": "BAS",
      "Trading Symbol": "BAS GR",
      "ratio": "2",
    },
    {
      "titulo": "Bayer AG",
      "simbolo": "BAYN",
      "Trading Symbol": "BAYN GR",
      "ratio": "3",
    },
    {
      "titulo": "BHP Group LTD",
      "simbolo": "BHP",
      "Trading Symbol": "BHP",
      "ratio": "2",
    },
    {
      "titulo": "Bilbao Vizcaya Argentaria S.A.",
      "simbolo": "BBV",
      "Trading Symbol": "BBVA",
      "ratio": "1",
    },
    {
      "titulo": "BIOGEN INC.",
      "simbolo": "BIIB",
      "Trading Symbol": "BIIB",
      "ratio": "13",
    },
    {
      "titulo": "BlackBerry Limited",
      "simbolo": "BB",
      "Trading Symbol": "BB",
      "ratio": "3",
    },
    {
      "titulo": "Boeing Co",
      "simbolo": "BA",
      "Trading Symbol": "BA",
      "ratio": "6",
    },
    {
      "titulo": "BP PLC",
      "simbolo": "BP",
      "Trading Symbol": "BP",
      "ratio": "5",
    },
    {
      "titulo": "BRF S.A.",
      "simbolo": "BRFS",
      "Trading Symbol": "BRFS",
      "ratio": "1:3",
    },
    {
      "titulo": "Bristol-Myers Squibb Company",
      "simbolo": "BMY",
      "Trading Symbol": "BMY",
      "ratio": "3",
    },
    {
      "titulo": "BUNGE LIMITED",
      "simbolo": "BNG",
      "Trading Symbol": "BG",
      "ratio": "5",
    },
    {
      "titulo": "Canon Inc",
      "simbolo": "CAJ",
      "Trading Symbol": "CAJ",
      "ratio": "2",
    },
    {
      "titulo": "Cardinal Health Inc",
      "simbolo": "CAH",
      "Trading Symbol": "CAH",
      "ratio": "3",
    },
    {
      "titulo": "Caterpillar Inc",
      "simbolo": "CAT",
      "Trading Symbol": "CAT",
      "ratio": "5",
    },
    {
      "titulo": "Cemex S.A.B. de CV",
      "simbolo": "CX",
      "Trading Symbol": "CX",
      "ratio": "1",
    },
    {
      "titulo": "CENTRAIS ELÉTRICAS BRASILEIRAS S.A. - ELETROBRÁS",
      "simbolo": "EBR",
      "Trading Symbol": "EBR",
      "ratio": "1:4",
    },
    {
      "titulo": "Chevron Corp.",
      "simbolo": "CVX",
      "Trading Symbol": "CVX",
      "ratio": "8",
    },
    {
      "titulo": "China Life Insurance",
      "simbolo": "LFC",
      "Trading Symbol": "LFC",
      "ratio": "2",
    },
    {
      "titulo": "CHINA MOBILE LTD.",
      "simbolo": "CHL",
      "Trading Symbol": "CHL",
      "ratio": "3",
    },
    {
      "titulo": "China Petroleum & Chem",
      "simbolo": "SNP",
      "Trading Symbol": "SNP",
      "ratio": "3",
    },
    {
      "titulo": "China Telecom Corp LTD",
      "simbolo": "CHA",
      "Trading Symbol": "CHA",
      "ratio": "2",
    },
    {
      "titulo": "Cisco Systems Inc",
      "simbolo": "CSCO",
      "Trading Symbol": "CSCO",
      "ratio": "5",
    },
    {
      "titulo": "Citigroup Inc",
      "simbolo": "C",
      "Trading Symbol": "C",
      "ratio": "3",
    },
    {
      "titulo": "CNOOC LTD.",
      "simbolo": "CEO",
      "Trading Symbol": "CEO",
      "ratio": "4",
    },
    {
      "titulo": "Coca-Cola Co.",
      "simbolo": "KO",
      "Trading Symbol": "KO",
      "ratio": "5",
    },
    {
      "titulo": "COCA-COLA FEMSA, S.A.B. De C.V..",
      "simbolo": "KOFM",
      "Trading Symbol": "KOF",
      "ratio": "2",
    },
    {
      "titulo": "Coeur Mining Inc.",
      "simbolo": "CDE",
      "Trading Symbol": "CDE",
      "ratio": "1",
    },
    {
      "titulo": "Colgate Palmolive Co",
      "simbolo": "CL",
      "Trading Symbol": "CL",
      "ratio": "3",
    },
    {
      "titulo": "COMPANHIA DE SANEAMENTO BÁSICO DO ESTADO DE SÃO PAULO–SABESP",
      "simbolo": "SBS",
      "Trading Symbol": "SBS",
      "ratio": "1:2",
    },
    {
      "titulo": "COMPANHIA PARANAENSE DE ENERGIA – COPEL",
      "simbolo": "ELP",
      "Trading Symbol": "ELP",
      "ratio": "1:3",
    },
    {
      "titulo": "COMPANHIA SIDERÚRGICA NACIONAL",
      "simbolo": "SID",
      "Trading Symbol": "SID",
      "ratio": "1:8",
    },
    {
      "titulo": "Corning Inc.",
      "simbolo": "GLW",
      "Trading Symbol": "GLW",
      "ratio": "4",
    },
    {
      "titulo": "Costco Wholesale Corp",
      "simbolo": "COST",
      "Trading Symbol": "COST",
      "ratio": "12",
    },
    {
      "titulo": "Credit Suisse Group",
      "simbolo": "CS",
      "Trading Symbol": "CS",
      "ratio": "1",
    },
    {
      "titulo": "TRIP.COM Group Ltd.​.",
      "simbolo": "TCOM",
      "Trading Symbol": "TCOM",
      "ratio": "2",
    },
    {
      "titulo": "Daimler AG",
      "simbolo": "DAI",
      "Trading Symbol": "DAI GR",
      "ratio": "4",
    },
    {
      "titulo": "DANONE",
      "simbolo": "BSN",
      "Trading Symbol": "BSN GR",
      "ratio": "20",
    },
    {
      "titulo": "Deere & Co.",
      "simbolo": "DE",
      "Trading Symbol": "DE",
      "ratio": "10",
    },
    {
      "titulo": "DESPEGAR.COM, CORP.",
      "simbolo": "DESP",
      "Trading Symbol": "DESP",
      "ratio": "1",
    },
    {
      "titulo": "Deutsche Telekom AG",
      "simbolo": "DTEA",
      "Trading Symbol": "DTEA GR",
      "ratio": "3",
    },
    {
      "titulo": "Diageo PLC",
      "simbolo": "DEO",
      "Trading Symbol": "DEO",
      "ratio": "6",
    },
    {
      "titulo": "DUPONT DE NOMOURS",
      "simbolo": "DD",
      "Trading Symbol": "DD",
      "ratio": "5",
    },
    {
      "titulo": "E.ON SE",
      "simbolo": "EOAN",
      "Trading Symbol": "EOAN GR",
      "ratio": "6",
    },
    {
      "titulo": "EBAY Inc.",
      "simbolo": "EBAY",
      "Trading Symbol": "EBAY",
      "ratio": "2",
    },
    {
      "titulo": "COMPANHIA BRASILEIRA DE DISTRIBUIÇÃO",
      "simbolo": "CBRD",
      "Trading Symbol": "CBD",
      "ratio": "1",
    },
    {
      "titulo": "Eli Lilly and Company",
      "simbolo": "LLY",
      "Trading Symbol": "LLY",
      "ratio": "8",
    },
    {
      "titulo": "EMBRAER-EMPRESA BRASILEIRA DE AERONÁUTICA S.A.",
      "simbolo": "ERJ",
      "Trading Symbol": "ERJ",
      "ratio": "1",
    },
    {
      "titulo": "ENI SpA",
      "simbolo": "E",
      "Trading Symbol": "E",
      "ratio": "4",
    },
    {
      "titulo": "Exxon Mobil Corporation",
      "simbolo": "XOM",
      "Trading Symbol": "XOM",
      "ratio": "5",
    },
    {
      "titulo": "FACEBOOK, INC.",
      "simbolo": "FB",
      "Trading Symbol": "FB",
      "ratio": "8",
    },
    {
      "titulo": "Fed. Natl, Mortgage - Fannie Mae",
      "simbolo": "FNMA",
      "Trading Symbol": "FNMA",
      "ratio": "1",
    },
    {
      "titulo": "FEDEX CORP",
      "simbolo": "FDX",
      "Trading Symbol": "FDX",
      "ratio": "10",
    },
    {
      "titulo": "First Solar Inc.",
      "simbolo": "FSLR",
      "Trading Symbol": "FSLR",
      "ratio": "3",
    },
    {
      "titulo": "Fomento Economico Mexicano - FEMSA",
      "simbolo": "FMX",
      "Trading Symbol": "FMX",
      "ratio": "2",
    },
    {
      "titulo": "Freddie Mac (Federal Home Loan)",
      "simbolo": "FMCC",
      "Trading Symbol": "FMCC",
      "ratio": "1",
    },
    {
      "titulo": "Freeport McMoran Copper & Gold Inc.",
      "simbolo": "FCX",
      "Trading Symbol": "FCX",
      "ratio": "1",
    },
    {
      "titulo": "GARMIN LTD.",
      "simbolo": "GRMN",
      "Trading Symbol": "GRMN",
      "ratio": "3",
    },
    {
      "titulo": "General Electric Co.",
      "simbolo": "GE",
      "Trading Symbol": "GE",
      "ratio": "1",
    },
    {
      "titulo": "GERDAU S.A.",
      "simbolo": "GGB",
      "Trading Symbol": "GGB",
      "ratio": "1:4",
    },
    {
      "titulo": "GILEAD SCIENCES, INC.",
      "simbolo": "GILD",
      "Trading Symbol": "GILD",
      "ratio": "4",
    },
    {
      "titulo": "GlaxoSmithkline plc",
      "simbolo": "GSK",
      "Trading Symbol": "GSK",
      "ratio": "4",
    },
    {
      "titulo": "GLOBANT S.A.",
      "simbolo": "GLNT",
      "Trading Symbol": "GLOB",
      "ratio": "6",
    },
    {
      "titulo": "Gold Fields Ltd.",
      "simbolo": "GFI",
      "Trading Symbol": "GFI",
      "ratio": "1",
    },
    {
      "titulo": "GRUPO AEROPORTUARIO DEL PACIFICO, S.A.B. de C.V.",
      "simbolo": "PAC",
      "Trading Symbol": "PAC",
      "ratio": "2",
    },
    {
      "titulo": "GRUPO AEROPORTUARIO DEL SURESTE , S.A.B. de C.V.",
      "simbolo": "ASR",
      "Trading Symbol": "ASR",
      "ratio": "2",
    },
    {
      "titulo": "Grupo Televisa S.A.",
      "simbolo": "TV",
      "Trading Symbol": "TV",
      "ratio": "3",
    },
    {
      "titulo": "Harley-Davidson Inc.",
      "simbolo": "HOG",
      "Trading Symbol": "HOG",
      "ratio": "3",
    },
    {
      "titulo": "HARMONY GOLD MINING COMPANY LTD.",
      "simbolo": "HMY",
      "Trading Symbol": "HMY",
      "ratio": "1",
    },
    {
      "titulo": "HDFC BANK LIMITED.",
      "simbolo": "HDB",
      "Trading Symbol": "HDB",
      "ratio": "2",
    },
    {
      "titulo": "Hecla Mining Co .",
      "simbolo": "HL",
      "Trading Symbol": "HL",
      "ratio": "1",
    },
    {
      "titulo": "Home Depot Inc., The",
      "simbolo": "HD",
      "Trading Symbol": "HD",
      "ratio": "8",
    },
    {
      "titulo": "Hon Hai Precision Industry Co. Ltd.",
      "simbolo": "HHPD",
      "Trading Symbol": "HHPD LI",
      "ratio": "2",
    },
    {
      "titulo": "Honda Motor Co. LTD",
      "simbolo": "HMC",
      "Trading Symbol": "HMC",
      "ratio": "1",
    },
    {
      "titulo": "HONEYWELL INTERNATIONAL INC.",
      "simbolo": "HON",
      "Trading Symbol": "HON",
      "ratio": "8",
    },
    {
      "titulo": "HP Inc",
      "simbolo": "HPQ",
      "Trading Symbol": "HPQ",
      "ratio": "1",
    },
    {
      "titulo": "HSBC Holdings PLC",
      "simbolo": "HSBC",
      "Trading Symbol": "HSBC",
      "ratio": "2",
    },
    {
      "titulo": "Huaneng Power Intl",
      "simbolo": "HNP",
      "Trading Symbol": "HNP",
      "ratio": "1",
    },
    {
      "titulo": "ICICI BANK LTD.",
      "simbolo": "IBN",
      "Trading Symbol": "IBN",
      "ratio": "1",
    },
    {
      "titulo": "Infosys Limited",
      "simbolo": "INFY",
      "Trading Symbol": "INFY",
      "ratio": "1",
    },
    {
      "titulo": "ING Groep NV",
      "simbolo": "ING",
      "Trading Symbol": "ING",
      "ratio": "3",
    },
    {
      "titulo": "Intel Corporation",
      "simbolo": "INTC",
      "Trading Symbol": "INTC",
      "ratio": "5",
    },
    {
      "titulo": "International Business Machines",
      "simbolo": "IBM",
      "Trading Symbol": "IBM",
      "ratio": "5",
    },
    {
      "titulo": "International Flavors & Fragrances Inc.",
      "simbolo": "IFF",
      "Trading Symbol": "IFF",
      "ratio": "2",
    },
    {
      "titulo": "International Paper Co.",
      "simbolo": "IP",
      "Trading Symbol": "IP",
      "ratio": "4",
    },
    {
      "titulo": "ITAÚ UNIBANCO HOLDING S.A.",
      "simbolo": "ITUB",
      "Trading Symbol": "ITUB",
      "ratio": "1",
    },
    {
      "titulo": "J.P. Morgan & Chase Co.",
      "simbolo": "JPM",
      "Trading Symbol": "JPM",
      "ratio": "5",
    },
    {
      "titulo": "JD.COM, INC.",
      "simbolo": "JD",
      "Trading Symbol": "JD",
      "ratio": "2",
    },
    {
      "titulo": "Johnson & Johnson",
      "simbolo": "JNJ",
      "Trading Symbol": "JNJ",
      "ratio": "5",
    },
    {
      "titulo": "JOHNSON CONTROLS INTERNATIONAL",
      "simbolo": "JCI",
      "Trading Symbol": "JCI",
      "ratio": "2",
    },
    {
      "titulo": "JOYY INC.",
      "simbolo": "YY",
      "Trading Symbol": "YY",
      "ratio": "5",
    },
    {
      "titulo": "KB Financial Group Inc.",
      "simbolo": "KB",
      "Trading Symbol": "KB",
      "ratio": "2",
    },
    {
      "titulo": "Kimberly-Clark Corp.",
      "simbolo": "KMB",
      "Trading Symbol": "KMB",
      "ratio": "6",
    },
    {
      "titulo": "Kinross Gold Corp",
      "simbolo": "KGC",
      "Trading Symbol": "KGC",
      "ratio": "1",
    },
    {
      "titulo": "Koninklijke Philips N.V.",
      "simbolo": "PHG",
      "Trading Symbol": "PHG",
      "ratio": "5",
    },
    {
      "titulo": "Korea Electric Power Corp.",
      "simbolo": "KEP",
      "Trading Symbol": "KEP",
      "ratio": "1",
    },
    {
      "titulo": "Las Vegas Sands Corp",
      "simbolo": "LVS",
      "Trading Symbol": "LVS",
      "ratio": "2",
    },
    {
      "titulo": "Lloyds Banking Group plc",
      "simbolo": "LYG",
      "Trading Symbol": "LYG",
      "ratio": "2",
    },
    {
      "titulo": "LM Ericsson Telephone Co.",
      "simbolo": "ERIC",
      "Trading Symbol": "ERIC",
      "ratio": "2",
    },
    {
      "titulo": "Lockheed Martin Corporation",
      "simbolo": "LMT",
      "Trading Symbol": "LMT",
      "ratio": "20",
    },
    {
      "titulo": "Marsh & McLennan Companies Inc.",
      "simbolo": "MMC",
      "Trading Symbol": "MMC",
      "ratio": "4",
    },
    {
      "titulo": "McDonald's Corp.",
      "simbolo": "MCD",
      "Trading Symbol": "MCD",
      "ratio": "8",
    },
    {
      "titulo": "MEDTRONIC PUBLIC LIMITED COMPANY",
      "simbolo": "MDT",
      "Trading Symbol": "MDT",
      "ratio": "4",
    },
    {
      "titulo": "MercadoLibre Inc.",
      "simbolo": "MELI",
      "Trading Symbol": "MELI",
      "ratio": "60",
    },
    {
      "titulo": "Merck & Co. Inc.",
      "simbolo": "MRK",
      "Trading Symbol": "MRK",
      "ratio": "5",
    },
    {
      "titulo": "Microsoft Corp",
      "simbolo": "MSFT",
      "Trading Symbol": "MSFT",
      "ratio": "10",
    },
    {
      "titulo": "Mitsubishi UFJ Financial Group",
      "simbolo": "MUFG",
      "Trading Symbol": "MUFG",
      "ratio": "1",
    },
    {
      "titulo": "Mizuho Financial Group",
      "simbolo": "MFG",
      "Trading Symbol": "MFG",
      "ratio": "1",
    },
    {
      "titulo": "Mobile Telesystems",
      "simbolo": "MBT",
      "Trading Symbol": "MBT",
      "ratio": "2",
    },
    {
      "titulo": "Motorola Solutions, Inc.",
      "simbolo": "MSI",
      "Trading Symbol": "MSI",
      "ratio": "5",
    },
    {
      "titulo": "National Grid PLC",
      "simbolo": "NGG",
      "Trading Symbol": "NGG",
      "ratio": "2",
    },
    {
      "titulo": "Nec Corporation",
      "simbolo": "NEC1",
      "Trading Symbol": "NEC1 GR",
      "ratio": "1:3",
    },
    {
      "titulo": "NETEASE, INC.",
      "simbolo": "NTES",
      "Trading Symbol": "NTES",
      "ratio": "14",
    },
    {
      "titulo": "NETFLIX, INC.",
      "simbolo": "NFLX",
      "Trading Symbol": "NFLX",
      "ratio": "16",
    },
    {
      "titulo": "Newmont Corporation",
      "simbolo": "NEM",
      "Trading Symbol": "NEM",
      "ratio": "3",
    },
    {
      "titulo": "Nike Inc.",
      "simbolo": "NKE",
      "Trading Symbol": "NKE",
      "ratio": "3",
    },
    {
      "titulo": "Nissan Motor Co., LTD",
      "simbolo": "NSAN",
      "Trading Symbol": "NSANY",
      "ratio": "1",
    },
    {
      "titulo": "Nokia Corporation",
      "simbolo": "NOKA",
      "Trading Symbol": "NOK",
      "ratio": "1",
    },
    {
      "titulo": "Nomura Holdings, Inc",
      "simbolo": "NMR",
      "Trading Symbol": "NMR",
      "ratio": "1",
    },
    {
      "titulo": "NOVAGOLD RESOURCES INC.",
      "simbolo": "NG",
      "Trading Symbol": "NG",
      "ratio": "1:4",
    },
    {
      "titulo": "Novartis AG",
      "simbolo": "NVS",
      "Trading Symbol": "NVS",
      "ratio": "4",
    },
    {
      "titulo": "NOVOLIPETSK STEEL PJSC",
      "simbolo": "NLM",
      "Trading Symbol": "NLMK LI",
      "ratio": "2",
    },
    {
      "titulo": "NTT Docomo, Inc",
      "simbolo": "DCMYY",
      "Trading Symbol": "DCMYY",
      "ratio": "1",
    },
    {
      "titulo": "Nucor Corp",
      "simbolo": "NUE",
      "Trading Symbol": "NUE",
      "ratio": "2",
    },
    {
      "titulo": "NVIDIA CORPORATION",
      "simbolo": "NVDA",
      "Trading Symbol": "NVDA",
      "ratio": "24",
    },
    {
      "titulo": "Oracle Corporation",
      "simbolo": "ORCL",
      "Trading Symbol": "ORCL",
      "ratio": "3",
    },
    {
      "titulo": "ORANGE",
      "simbolo": "ORAN",
      "Trading Symbol": "ORAN",
      "ratio": "1",
    },
    {
      "titulo": "Paccar Inc.",
      "simbolo": "PCAR",
      "Trading Symbol": "PCAR",
      "ratio": "3",
    },
    {
      "titulo": "Panasonic Corporation",
      "simbolo": "PCRF",
      "Trading Symbol": "PCRFY",
      "ratio": "2",
    },
    {
      "titulo": "PAYPAL HOLDINGS, INC.",
      "simbolo": "PYPL",
      "Trading Symbol": "PYPL",
      "ratio": "8",
    },
    {
      "titulo": "Pearson PLC",
      "simbolo": "PSO",
      "Trading Symbol": "PSO",
      "ratio": "1",
    },
    {
      "titulo": "Pepsico Inc",
      "simbolo": "PEP",
      "Trading Symbol": "PEP",
      "ratio": "6",
    },
    {
      "titulo": "PETROBRAS (ADR)",
      "simbolo": "PBR",
      "Trading Symbol": "PBR",
      "ratio": "1",
    },
    {
      "titulo": "Petrochina Co Ltd",
      "simbolo": "PTR",
      "Trading Symbol": "PTR",
      "ratio": "4",
    },
    {
      "titulo": "Pfizer Inc.",
      "simbolo": "PFE",
      "Trading Symbol": "PFE",
      "ratio": "2",
    },
    {
      "titulo": "Pitney Bowes Inc",
      "simbolo": "PBI",
      "Trading Symbol": "PBI",
      "ratio": "1",
    },
    {
      "titulo": "PJSC GAZPROM",
      "simbolo": "OGZD",
      "Trading Symbol": "OGZD",
      "ratio": "2",
    },
    {
      "titulo": "PJSC LUKOIL",
      "simbolo": "LKOD",
      "Trading Symbol": "LKOD",
      "ratio": "4",
    },
    {
      "titulo": "PJSC TATNEFT",
      "simbolo": "ATAD",
      "Trading Symbol": "ATAD",
      "ratio": "4",
    },
    {
      "titulo": "POSCO",
      "simbolo": "PKS",
      "Trading Symbol": "PKX",
      "ratio": "3",
    },
    {
      "titulo": "Procter & Gamble",
      "simbolo": "PG",
      "Trading Symbol": "PG",
      "ratio": "5",
    },
    {
      "titulo": "Qualcomm Inc.",
      "simbolo": "QCOM",
      "Trading Symbol": "QCOM",
      "ratio": "11",
    },
    {
      "titulo": "Rio Tinto PLC",
      "simbolo": "RIO",
      "Trading Symbol": "RIO",
      "ratio": "4",
    },
    {
      "titulo": "ROSS STORES, INC.",
      "simbolo": "ROST",
      "Trading Symbol": "ROST",
      "ratio": "4",
    },
    {
      "titulo": "Royal Dutch Shell PLC",
      "simbolo": "RDS",
      "Trading Symbol": "RDSB",
      "ratio": "2",
    },
    {
      "titulo": "SALESFORCE.COM, INC.",
      "simbolo": "CRM",
      "Trading Symbol": "CRM",
      "ratio": "6",
    },
    {
      "titulo": "SAMSUNG ELECTRONICS CO. LTD.",
      "simbolo": "SMSN",
      "Trading Symbol": "SMSN LI",
      "ratio": "14",
    },
    {
      "titulo": "SAP SE",
      "simbolo": "SAP",
      "Trading Symbol": "SAP",
      "ratio": "6",
    },
    {
      "titulo": "Schlumberger Ltd",
      "simbolo": "SLB",
      "Trading Symbol": "SLB",
      "ratio": "3",
    },
    {
      "titulo": "Siemens AG ADR",
      "simbolo": "SIEGY",
      "Trading Symbol": "SIEGY",
      "ratio": "3",
    },
    {
      "titulo": "SNAP INC.",
      "simbolo": "SNAP",
      "Trading Symbol": "SNAP",
      "ratio": "1",
    },
    {
      "titulo": "Snap-On Inc",
      "simbolo": "SNA",
      "Trading Symbol": "SNA",
      "ratio": "6",
    },
    {
      "titulo": "Sony Corporation",
      "simbolo": "SNE",
      "Trading Symbol": "SNE",
      "ratio": "4",
    },
    {
      "titulo": "Southern Copper Corp",
      "simbolo": "SCCO",
      "Trading Symbol": "SCCO",
      "ratio": "2",
    },
    {
      "titulo": "Starbucks Corporation",
      "simbolo": "SBUX",
      "Trading Symbol": "SBUX",
      "ratio": "4",
    },
    {
      "titulo": "SUZANO PAPEL E CELULOSE S.A.",
      "simbolo": "SUZ",
      "Trading Symbol": "SUZ",
      "ratio": "1",
    },
    {
      "titulo": "Sysco Corp.",
      "simbolo": "SYY",
      "Trading Symbol": "SYY",
      "ratio": "2",
    },
    {
      "titulo": "Taiwan Semiconductor Manufacturing",
      "simbolo": "TSM",
      "Trading Symbol": "TSM",
      "ratio": "1:3",
    },
    {
      "titulo": "TARGET CORPORATION",
      "simbolo": "TGT",
      "Trading Symbol": "TGT",
      "ratio": "4",
    },
    {
      "titulo": "TATA MOTORS LTD",
      "simbolo": "TTM",
      "Trading Symbol": "TTM",
      "ratio": "1",
    },
    {
      "titulo": "Telecom Italia S.P.A. Ordinary Shares",
      "simbolo": "TIIAY",
      "Trading Symbol": "TIIAY",
      "ratio": "1",
    },
    {
      "titulo": "TELEFÔNICA BRASIL S.A.",
      "simbolo": "VIV",
      "Trading Symbol": "VIV",
      "ratio": "1",
    },
    {
      "titulo": "Telefonica S.A.",
      "simbolo": "TEFO",
      "Trading Symbol": "TEF",
      "ratio": "8",
    },
    {
      "titulo": "TENARIS",
      "simbolo": "TEN",
      "Trading Symbol": "TS",
      "ratio": "1",
    },
    {
      "titulo": "TERNIUM S.A.",
      "simbolo": "TXR",
      "Trading Symbol": "TX",
      "ratio": "2",
    },
    {
      "titulo": "TESLA, INC.",
      "simbolo": "TSLA",
      "Trading Symbol": "TSLA",
      "ratio": "15",
    },
    {
      "titulo": "Texas Instruments Inc",
      "simbolo": "TXN",
      "Trading Symbol": "TXN",
      "ratio": "5",
    },
    {
      "titulo": "THE BANK OF NEW YORK MELLON CORP.",
      "simbolo": "BK",
      "Trading Symbol": "BK",
      "ratio": "2",
    },
    {
      "titulo": "THE GOLDMAN SACHS GROUP, INC",
      "simbolo": "GS",
      "Trading Symbol": "GS",
      "ratio": "13",
    },
    {
      "titulo": "THE HERSHEY COMPANY",
      "simbolo": "HSY",
      "Trading Symbol": "HSY",
      "ratio": "3",
    },
    {
      "titulo": "THE WALT DISNEY CO.",
      "simbolo": "DISN",
      "Trading Symbol": "DIS",
      "ratio": "4",
    },
    {
      "titulo": "THERMO FISHER SCIENTIFIC INC.",
      "simbolo": "TMO",
      "Trading Symbol": "TMO",
      "ratio": "22",
    },
    {
      "titulo": "TIM PARTICIPAÇÕES S.A.",
      "simbolo": "TSU",
      "Trading Symbol": "TIMB",
      "ratio": "1",
    },
    {
      "titulo": "TOTAL S.E.",
      "simbolo": "TOT",
      "Trading Symbol": "TOT",
      "ratio": "3",
    },
    {
      "titulo": "Toyota Motor Corporation",
      "simbolo": "TM",
      "Trading Symbol": "TM",
      "ratio": "5",
    },
    {
      "titulo": "The Travelers Companies, Inc.",
      "simbolo": "TRVV",
      "Trading Symbol": "TRV",
      "ratio": "6",
    },
    {
      "titulo": "TRIPADVISOR, INC.",
      "simbolo": "TRIP",
      "Trading Symbol": "TRIP",
      "ratio": "2",
    },
    {
      "titulo": "TWITTER, INC.",
      "simbolo": "TWTR",
      "Trading Symbol": "TWTR",
      "ratio": "2",
    },
    {
      "titulo": "U.S. BANCORP",
      "simbolo": "USB",
      "Trading Symbol": "USB",
      "ratio": "1",
    },
    {
      "titulo": "ULTRAPAR PARTICIPAÇÕES S.A.",
      "simbolo": "UGP",
      "Trading Symbol": "UGP",
      "ratio": "1",
    },
    {
      "titulo": "UNILEVER N.V.",
      "simbolo": "UN",
      "Trading Symbol": "UN",
      "ratio": "3",
    },
    {
      "titulo": "United States Steel Corp.",
      "simbolo": "X",
      "Trading Symbol": "X",
      "ratio": "3",
    },
    {
      "titulo": "RAYTHEON TECHNOLOGIES CORP USD 0.01",
      "simbolo": "RTX",
      "Trading Symbol": "RTX",
      "ratio": "5",
    },
    {
      "titulo": "URBAN OUTFITTERS, INC.",
      "simbolo": "URBN",
      "Trading Symbol": "URBN",
      "ratio": "2",
    },
    {
      "titulo": "Vale S.A.",
      "simbolo": "VALE",
      "Trading Symbol": "VALE",
      "ratio": "2",
    },
    {
      "titulo": "VEDANTA LIMITED",
      "simbolo": "VEDL",
      "Trading Symbol": "VEDL",
      "ratio": "1",
    },
    {
      "titulo": "VERISIGN, INC.",
      "simbolo": "VRSN",
      "Trading Symbol": "VRSN",
      "ratio": "6",
    },
    {
      "titulo": "Verizon Communications Inc.",
      "simbolo": "VZ",
      "Trading Symbol": "VZ",
      "ratio": "2",
    },
    {
      "titulo": "VISA INC",
      "simbolo": "V",
      "Trading Symbol": "V",
      "ratio": "6",
    },
    {
      "titulo": "VISTA OIL & GAS SAB DE CV (ADS)",
      "simbolo": "VIST",
      "Trading Symbol": "VIST US",
      "ratio": "1:5",
    },
    {
      "titulo": "Vodafone Group PLC",
      "simbolo": "VOD",
      "Trading Symbol": "VOD",
      "ratio": "1",
    },
    {
      "titulo": "WALMART Inc.",
      "simbolo": "WMT",
      "Trading Symbol": "WMT",
      "ratio": "6",
    },
    {
      "titulo": "WEIBO CORPORATION",
      "simbolo": "WBO",
      "Trading Symbol": "WB",
      "ratio": "6",
    },
    {
      "titulo": "Wells Fargo & Co.",
      "simbolo": "WFC",
      "Trading Symbol": "WFC",
      "ratio": "5",
    },
    {
      "titulo": "Westpac Banking Corporation",
      "simbolo": "WBK",
      "Trading Symbol": "WBK",
      "ratio": "3",
    },
    {
      "titulo": "XEROX HOLDING CORPORATION",
      "simbolo": "XROX",
      "Trading Symbol": "XRX",
      "ratio": "1",
    },
    {
      "titulo": "Yamana Gold Inc.",
      "simbolo": "AUY",
      "Trading Symbol": "AUY",
      "ratio": "1",
    },
    {
      "titulo": "YANZHOU COAL MINING CO. LTD.",
      "simbolo": "YZCA",
      "Trading Symbol": "YZCAY",
      "ratio": "2",
    },
    {
      "titulo": "YELP INC.",
      "simbolo": "YELP",
      "Trading Symbol": "YELP",
      "ratio": "2",
    }
   ]